"""
Django settings for spicyx project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spicyxapp',
    'django.contrib.admin',
    'django.contrib.auth',

    'storages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spicyx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spicyx.wsgi.application'


# Database - DEV
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# AWS FILES CONFIGURATIONS
USE_S3 = True
if USE_S3:
    # AWS SETTINGS
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_STORAGE_BUCKET_NAME = ''
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    DEFAULT_FILE_STORAGE = 'spicyxapp.STORAGE_S3.PrivateBucket'
    BUCKET_NAME = AWS_STORAGE_BUCKET_NAME

# AWS PUBLIC FOR STATIC FILES
USE_PUBLIC_BUCKET = False
if USE_PUBLIC_BUCKET:
    # S3 PUBLIC STATIC SETTINGS
    STATIC_URL = 'https://.s3.amazonaws.com/static/'
    STATICFILES_STORAGE = 'spicyxapp.STORAGE_S3.StaticBucket'
else:
    STATIC_URL = 'spicyxapp/static/'
    STATIC_ROOT = 'spicyxapp/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'


# Descomentar as linhas abaixo referente a segurança quando em produção
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True


# Configurações do servidor de e-mail
# DEFAULT_FROM_EMAIL = '@steste.com'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_PORT = 465
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')


DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 #10Mb


# Panda video
PANDA_VIDEO_API_KEY = config('PANDA_VIDEO_API_KEY')


ALLOWED_EXTENSIONS_IMAGES = ['jpg', 'jpeg', 'png', 'gif']
IMAGE_SIZE_LIMIT_POST = 100 * 1024 * 1024
IMAGE_SIZE_LIMIT_AVATAR = 10 * 1024 * 1024
ALLOWED_DOCS_CREATORS_EXTENSIONS = ['jpg', 'png', 'pdf']
DOCS_CREATORS_SIZE_LIMIT = 10 * 1024 * 1024
IMAGE_SIZE_LIMIT_COVER = IMAGE_SIZE_LIMIT_AVATAR
ALLOWED_EXTENSIONS_VIDEOS = ['avi', '3gp', 'mp4']
VIDEO_SIZE_LIMITE = 1000 * 1024 * 1024


# STRIPE SETTINGS
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOKS_SECRET')
STRIPE_SECRET_API_KEY = config('STRIPE_SECRET_API_KEY')

